esphome:esphome:
  includes:
    - displays/components/notification_manager.h
  name: ${devicename}
  friendly_name: ${friendly_name}
  min_version: 2025.11.2

logger:
  level: $loglevel

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .fritz.box
  min_auth_mode: WPA2

ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption:
    key: !secret encrypt_key
  reboot_timeout: 180s

