esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0

logger:
  level: $loglevel

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .fritz.box

ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption:
    key: !secret encrypt_key
  reboot_timeout: 180s

