interval:
  - interval: 5s
    then:
      - script.execute: notification_label_loop

script:
  - id: notification_add
    parameters:
      id_str: string
      text: string
    then:
      - lambda: |-
          auto &mgr = esphome::NotificationManager::instance();
          mgr.add_notification(id_str, text);

  - id: notification_remove
    parameters:
      id_str: string
    then:
      - lambda: |-
          auto &mgr = esphome::NotificationManager::instance();
          mgr.remove_notification(id_str);

  - id: notification_label_loop
    then:
      - if:
          condition:
            lambda: |-
              auto &mgr = esphome::NotificationManager::instance();
              mgr.rotate();
              return id(standby_active).state && mgr.is_dirty();
          then:
            - lvgl.label.update:
                id: standby_notification_local_label
                text: !lambda |-
                  auto &mgr = esphome::NotificationManager::instance();
                  mgr.clear_dirty();
                  if (mgr.has_notifications()) {
                    return mgr.get_current_text();
                  }
                  return std::string("");

binary_sensor:
  - platform: template
    id: standby_active
    name: "Standby Active"
    internal: true
    on_state:
      then:
        - if:
            condition:
              lambda: |-
                return id(standby_active).state;
            then:
              - lvgl.widget.show:
                  id: standby_screen
              - script.execute: notification_label_loop
            else:
              - lvgl.widget.hide:
                  id: standby_screen

number:
  - platform: template
    name: Standby brightness
    optimistic: true
    id: standby_brightness
    unit_of_measurement: "%"
    initial_value: 40
    restore_value: true
    min_value: 10
    max_value: 100
    step: 5
    mode: box

lvgl:
  top_layer:
    widgets:
      - obj: 
          <<: !include ../layout/grid/main.yaml
          id: standby_screen
          layout:
            <<: !include ../layout/grid/layout.yaml
            grid_rows: [FR(2), FR(1), FR(1), FR(1), FR(1)]
            grid_columns: [FR(1), FR(1)]
          widgets:
            - label:
                <<: !include 
                  file: ../layout/grid/label_cell.yaml
                  vars: 
                    x: 0
                    y: 0
                    colspan: 2
                    text: "00:00"
                    font_size: xxl
                id: standby_clock
            - label:
                <<: !include 
                  file: ../layout/grid/label_cell.yaml
                  vars: 
                    x: 0
                    y: 1
                    x_align: CENTER
                    y_align: END
                    colspan: 2
                    font_size: lg
                id: standby_weather_condition_label
            - label:
                <<: !include 
                  file: ../layout/grid/label_cell.yaml
                  vars: 
                    x: 0
                    y: 2
                    x_align: CENTER
                    y_align: START
                    colspan: 2
                id: standby_weather_temperature_label
            - label:
                <<: !include 
                  file: ../layout/grid/label_cell.yaml
                  vars: 
                    x: 0
                    y: 3
                    colspan: 2
                    font_size: lg
                text_color: 0xff0000
                id: standby_notification_local_label

          on_press:
            then:
              - script.execute: go_home