packages:
  weather_config: !include ../config/weather_config.yaml
  common: !include 
    file: common.yaml
    vars:
      page_id: weather_page
      page_title: ${weather_page_title}

text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: ${weather_condition_sensor}
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return x == "clear-night";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f34f"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_clear_night}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f34f ${weather_clear_night}"
        - if:
            condition:
              lambda: 'return x == "cloudy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000e2bd"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_cloudy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000e2bd ${weather_cloudy}"
        - if:
            condition:
              lambda: 'return x == "exceptional";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000ebd5"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_exceptional}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000ebd5 ${weather_exceptional}"
        - if:
            condition:
              lambda: 'return x == "fog";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000e188"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_fog}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000e188 ${weather_fog}"
        - if:
            condition:
              lambda: 'return x == "hail";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f67f"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_hail}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f67f ${weather_hail}"
        - if:
            condition:
              lambda: 'return x == "snowy-rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f67f"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_snowy_rainy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f67f ${weather_snowy_rainy}"
        - if:
            condition:
              lambda: 'return x == "lightning" || x == "lightning-rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000ebdb"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_lightning}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000ebdb ${weather_lightning}"
        - if:
            condition:
              lambda: 'return x == "partlycloudy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f172"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_partlycloudy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f172 ${weather_partlycloudy}"
        - if:
            condition:
              lambda: 'return x == "pouring";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f61f"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_pouring}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f61f ${weather_pouring}"
        - if:
            condition:
              lambda: 'return x == "rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000f176"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_rainy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000f176 ${weather_rainy}"
        - if:
            condition:
              lambda: 'return x == "snowy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000e2cd"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_snowy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000e2cd ${weather_snowy}"
        - if:
            condition:
              lambda: 'return x == "sunny";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000e81a"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_sunny}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000e81a ${weather_sunny}"
        - if:
            condition:
              lambda: 'return x == "windy" || x == "windy-variant";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: "\U0000efd8"
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_windy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "\U0000efd8 ${weather_windy}"
                
sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: ${weather_temperature_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature
          text:
            format: "%.1f"
            args: [ 'x' ]
      - lvgl.label.update:
          id: standby_weather_temperature_label
          text:
            format: "\U0000e846 %.1f ${temperature_unit}"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_min
    entity_id: ${weather_temperature_min_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_min
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_max
    entity_id: ${weather_temperature_max_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_max
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_humidity
    entity_id: ${weather_humidity_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_humidity
          text:
            format: "%.0f"
            args: [ 'x' ]

lvgl:
  pages:
    - id: !extend weather_page
      widgets:
        - obj:
            <<: !include ../layout/grid/main.yaml
            layout:
              <<: !include ../layout/grid/layout.yaml
              grid_rows: [FR(1)]
              grid_columns: [FR(2), FR(3)]
            widgets:
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 0
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(5), FR(1)]
                    grid_columns: [FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            y_align: START
                            text: "\U0000e2c1"
                        id: icon_weather_condition
                        text_font: mdi_xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            y_align: START
                            font_size: sm
                            text: "Lädt..."
                        id: state_weather_condition
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 1
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(3), FR(1), FR(1), FR(1)]
                    grid_columns: [FR(1), FR(1), FR(1), FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            colspan: 3
                            x_align: END
                            font_size: xxl
                        id: state_weather_temperature
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars:
                            x: 3
                            y: 0
                            x_align: START
                            text: ${temperature_unit}
                            font_size: xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            x_align: START
                            text: "\U0000e846 ${weather_temperature_min_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 1
                            x_align: END
                        id: state_weather_temperature_min
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 1
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 2
                            x_align: START
                            text: "\U0000e846 ${weather_temperature_max_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 2
                            x_align: END
                        id: state_weather_temperature_max
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 2
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 3
                            colspan: 2
                            x_align: START
                            text: "\U0000f164 ${humidity_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 3
                            x_align: END
                        id: state_weather_humidity
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 3
                            x_align: START
                            text: "%"