packages:
  common: !include 
    file: common.yaml
    vars:
      page_id: weather_page
      page_title: ${weather_page_title}

mapping:
  - id: weather_icon
    from: string
    to: string
    entries:
      clear-night: ${mdo_clear_night}
      cloudy: ${mdo_cloudy}
      exceptional: ${mdo_exceptional}
      fog: ${mdo_fog}
      hail: ${mdo_hail}
      lightning: ${mdo_lightning}
      lightning-rainy: ${mdo_lightning}
      partlycloudy: ${mdo_partlycloudy}
      pouring: ${mdo_pouring}
      rainy: ${mdo_rainy}
      snowy: ${mdo_snowy}
      snowy-rainy: ${mdo_hail}
      sunny: ${mdo_sunny}
      windy: ${mdo_windy}
      windy-variant: ${mdo_windy}
  - id: weather_condition_translation
    from: string
    to: string
    entries:
      clear-night: ${weather_clear_night}
      cloudy: ${weather_cloudy}
      exceptional: ${weather_exceptional}
      fog: ${weather_fog}
      hail: ${weather_hail}
      lightning: ${weather_lightning}
      lightning-rainy: ${weather_lightning}
      partlycloudy: ${weather_partlycloudy}
      pouring: ${weather_pouring}
      rainy: ${weather_rainy}
      snowy: ${weather_snowy}
      snowy-rainy: ${weather_snowy_rainy}
      sunny: ${weather_sunny}
      windy: ${weather_windy}
      windy-variant: ${weather_windy}
  - id: weather_icon_and_condition_translation
    from: string
    to: string
    entries:
      clear-night: "${mdo_clear_night} ${weather_clear_night}"
      cloudy: "${mdo_cloudy} ${weather_cloudy}"
      exceptional: "${mdo_exceptional} ${weather_exceptional}"
      fog: "${mdo_fog} ${weather_fog}"
      hail: "${mdo_hail} ${weather_hail}"
      lightning: "${mdo_lightning} ${weather_lightning}"
      lightning-rainy: "${mdo_lightning} ${weather_lightning}"
      partlycloudy: "${mdo_partlycloudy} ${weather_partlycloudy}"
      pouring: "${mdo_pouring} ${weather_pouring}"
      rainy: "${mdo_rainy} ${weather_rainy}"
      snowy: "${mdo_snowy} ${weather_snowy}"
      snowy-rainy: "${mdo_hail} ${weather_snowy_rainy}"
      sunny: "${mdo_sunny} ${weather_sunny}"
      windy: "${mdo_windy} ${weather_windy}"
      windy-variant: "${mdo_windy} ${weather_windy}"

text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: ${weather_condition_sensor}
    on_value: 
      then:
        - lvgl.label.update:
            id: icon_weather_condition
            text: !lambda return id(weather_icon)[x];
        - lvgl.label.update:
            id: state_weather_condition
            text: !lambda return id(weather_condition_translation)[x];
        - lvgl.label.update:
            id: standby_weather_condition_label
            text: !lambda return id(weather_icon_and_condition_translation)[x];
                
sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: ${weather_temperature_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature
          text:
            format: "%.1f"
            args: [ 'x' ]
      - lvgl.label.update:
          id: standby_weather_temperature_label
          text:
            format: "${mdo_thermometer} %.1f ${temperature_unit}"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_min
    entity_id: ${weather_temperature_min_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_min
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_max
    entity_id: ${weather_temperature_max_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_max
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_humidity
    entity_id: ${weather_humidity_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_humidity
          text:
            format: "%.0f"
            args: [ 'x' ]

lvgl:
  pages:
    - id: !extend weather_page
      widgets:
        - obj:
            <<: !include ../layout/grid/main.yaml
            layout:
              <<: !include ../layout/grid/layout.yaml
              grid_rows: [FR(1)]
              grid_columns: [FR(2), FR(3)]
            widgets:
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 0
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(5), FR(1)]
                    grid_columns: [FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            y_align: START
                            text: ${mdo_cloud_off}
                        id: icon_weather_condition
                        text_font: mdi_xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            y_align: START
                            font_size: sm
                            text: "Lädt..."
                        id: state_weather_condition
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 1
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(3), FR(1), FR(1), FR(1)]
                    grid_columns: [FR(1), FR(1), FR(1), FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            colspan: 3
                            x_align: END
                            font_size: xxl
                        id: state_weather_temperature
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars:
                            x: 3
                            y: 0
                            x_align: START
                            text: ${temperature_unit}
                            font_size: xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            x_align: START
                            text: "${mdo_thermometer} ${weather_temperature_min_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 1
                            x_align: END
                        id: state_weather_temperature_min
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 1
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 2
                            x_align: START
                            text: "${mdo_thermometer} ${weather_temperature_max_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 2
                            x_align: END
                        id: state_weather_temperature_max
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 2
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 3
                            colspan: 2
                            x_align: START
                            text: "${mdo_humidity} ${humidity_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 3
                            x_align: END
                        id: state_weather_humidity
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 3
                            x_align: START
                            text: "%"