packages:
  common: !include 
    file: common.yaml
    vars:
      page_id: weather_page
      page_title: ${weather_page_title}

text_sensor:
  - platform: homeassistant
    id: weather_condition
    entity_id: ${weather_condition_sensor}
    on_value: 
      then:
        - if:
            condition:
              lambda: 'return x == "clear-night";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_clear_night}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_clear_night}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_clear_night} ${weather_clear_night}"
        - if:
            condition:
              lambda: 'return x == "cloudy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_cloudy}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_cloudy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_cloudy} ${weather_cloudy}"
        - if:
            condition:
              lambda: 'return x == "exceptional";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_exceptional}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_exceptional}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_exceptional} ${weather_exceptional}"
        - if:
            condition:
              lambda: 'return x == "fog";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_fog}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_fog}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_fog} ${weather_fog}"
        - if:
            condition:
              lambda: 'return x == "hail";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_hail}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_hail}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_hail} ${weather_hail}"
        - if:
            condition:
              lambda: 'return x == "snowy-rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_hail}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_snowy_rainy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_hail} ${weather_snowy_rainy}"
        - if:
            condition:
              lambda: 'return x == "lightning" || x == "lightning-rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_lightning}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_lightning}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_lightning} ${weather_lightning}"
        - if:
            condition:
              lambda: 'return x == "partlycloudy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_partlycloudy}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_partlycloudy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_partlycloudy} ${weather_partlycloudy}"
        - if:
            condition:
              lambda: 'return x == "pouring";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_pouring}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_pouring}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_pouring} ${weather_pouring}"
        - if:
            condition:
              lambda: 'return x == "rainy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_rainy}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_rainy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_rainy} ${weather_rainy}"
        - if:
            condition:
              lambda: 'return x == "snowy";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_snowy}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_snowy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_snowy} ${weather_snowy}"
        - if:
            condition:
              lambda: 'return x == "sunny";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_sunny}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_sunny}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_sunny} ${weather_sunny}"
        - if:
            condition:
              lambda: 'return x == "windy" || x == "windy-variant";'
            then:
              - lvgl.label.update:
                  id: icon_weather_condition
                  text: ${mdo_windy}
              - lvgl.label.update:
                  id: state_weather_condition
                  text: ${weather_windy}
              - lvgl.label.update:
                  id: standby_weather_condition_label
                  text: "${mdo_windy} ${weather_windy}"
                
sensor:
  - platform: homeassistant
    id: weather_temperature
    entity_id: ${weather_temperature_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature
          text:
            format: "%.1f"
            args: [ 'x' ]
      - lvgl.label.update:
          id: standby_weather_temperature_label
          text:
            format: "${mdo_thermometer} %.1f ${temperature_unit}"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_min
    entity_id: ${weather_temperature_min_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_min
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_temperature_max
    entity_id: ${weather_temperature_max_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_temperature_max
          text:
            format: "%.1f"
            args: [ 'x' ]
  - platform: homeassistant
    id: weather_humidity
    entity_id: ${weather_humidity_sensor}
    on_value:
      - lvgl.label.update:
          id: state_weather_humidity
          text:
            format: "%.0f"
            args: [ 'x' ]

lvgl:
  pages:
    - id: !extend weather_page
      widgets:
        - obj:
            <<: !include ../layout/grid/main.yaml
            layout:
              <<: !include ../layout/grid/layout.yaml
              grid_rows: [FR(1)]
              grid_columns: [FR(2), FR(3)]
            widgets:
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 0
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(5), FR(1)]
                    grid_columns: [FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            y_align: START
                            text: ${mdo_cloud_off}
                        id: icon_weather_condition
                        text_font: mdi_xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            y_align: START
                            font_size: sm
                            text: "Lädt..."
                        id: state_weather_condition
              - obj:
                  <<: !include 
                    file: ../layout/grid/cell.yaml 
                    vars: 
                      x: 1
                      y: 0
                      pad_all: ${GRID_PADDING}
                  layout:
                    <<: !include ../layout/grid/layout.yaml
                    grid_rows: [FR(3), FR(1), FR(1), FR(1)]
                    grid_columns: [FR(1), FR(1), FR(1), FR(1)]
                  border_width: 0
                  widgets:
                    - label:
                        <<: !include
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 0
                            colspan: 3
                            x_align: END
                            font_size: xxl
                        id: state_weather_temperature
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars:
                            x: 3
                            y: 0
                            x_align: START
                            text: ${temperature_unit}
                            font_size: xl
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 1
                            x_align: START
                            text: "${mdo_thermometer} ${weather_temperature_min_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 1
                            x_align: END
                        id: state_weather_temperature_min
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 1
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 2
                            x_align: START
                            text: "${mdo_thermometer} ${weather_temperature_max_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 2
                            x_align: END
                        id: state_weather_temperature_max
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 2
                            x_align: START
                            text: ${temperature_unit}
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 0
                            y: 3
                            colspan: 2
                            x_align: START
                            text: "${mdo_humidity} ${humidity_label}"
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 2
                            y: 3
                            x_align: END
                        id: state_weather_humidity
                    - label:
                        <<: !include 
                          file: ../layout/grid/label_cell.yaml
                          vars: 
                            x: 3
                            y: 3
                            x_align: START
                            text: "%"